# Generated by Django 4.2.7 on 2026-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cin',
            field=models.CharField(blank=True, max_length=21, null=True, verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='employee_size',
            field=models.CharField(blank=True, choices=[('1-10', '1-10'), ('11-50', '11-50'), ('51-200', '51-200'), ('201-500', '201-500'), ('501-1000', '501-1000'), ('1000+', '1000+')], max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='gstin',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='GSTIN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(blank=True, choices=[('technology', 'Technology'), ('manufacturing', 'Manufacturing'), ('retail', 'Retail'), ('healthcare', 'Healthcare'), ('finance', 'Finance & Banking'), ('education', 'Education'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality'), ('logistics', 'Logistics'), ('agriculture', 'Agriculture'), ('textile', 'Textile'), ('pharma', 'Pharmaceuticals'), ('automotive', 'Automotive'), ('fmcg', 'FMCG'), ('construction', 'Construction'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PAN'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='aadhaar_last4',
            field=models.CharField(blank=True, help_text='Last 4 digits only', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='salutation',
            field=models.CharField(blank=True, choices=[('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms.'), ('dr', 'Dr.'), ('prof', 'Prof.')], max_length=10),
        ),
        migrations.AlterField(
            model_name='contactactivity',
            name='activity_type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('whatsapp', 'WhatsApp'), ('note', 'Note'), ('task', 'Task')], max_length=20),
        ),
        migrations.AlterField(
            model_name='contactactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='contactdocument',
            name='doc_type',
            field=models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('pan', 'PAN Card'), ('passport', 'Passport'), ('driving_license', 'Driving License'), ('gst_certificate', 'GST Certificate'), ('incorporation', 'Certificate of Incorporation'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contactdocument',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
