# Generated by Django 4.2.7 on 2026-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, help_text='Deep link in app', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('lead_assigned', 'Lead Assigned'), ('deal_stage_changed', 'Deal Stage Changed'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_sla_breach', 'Ticket SLA Breach'), ('deal_close_approaching', 'Deal Close Approaching'), ('workflow_alert', 'Workflow Alert'), ('payment_received', 'Payment Received'), ('quote_accepted', 'Quote Accepted'), ('mention', 'Mentioned'), ('system', 'System')], max_length=40),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='todo', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('follow_up', 'Follow Up'), ('demo', 'Demo'), ('other', 'Other')], default='follow_up', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='run_once_per_object',
            field=models.BooleanField(default=True, help_text='Prevent duplicate runs'),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='trigger',
            field=models.CharField(choices=[('lead_created', 'Lead Created'), ('lead_status_changed', 'Lead Status Changed'), ('lead_assigned', 'Lead Assigned'), ('lead_priority_changed', 'Lead Priority Changed'), ('deal_created', 'Deal Created'), ('deal_stage_changed', 'Deal Stage Changed'), ('deal_won', 'Deal Won'), ('deal_lost', 'Deal Lost'), ('deal_close_date_reached', 'Deal Close Date Reached'), ('contact_created', 'Contact Created'), ('ticket_created', 'Ticket Created'), ('ticket_status_changed', 'Ticket Status Changed'), ('ticket_sla_breached', 'Ticket SLA Breached'), ('ticket_resolved', 'Ticket Resolved'), ('scheduled', 'Scheduled (Time-based)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflow',
            name='trigger_config',
            field=models.JSONField(blank=True, default=dict, help_text='Filter conditions for trigger e.g. {status: "won"}'),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='action_type',
            field=models.CharField(choices=[('assign_owner', 'Assign Owner'), ('assign_round_robin', 'Assign Round Robin'), ('update_lead_status', 'Update Lead Status'), ('update_deal_stage', 'Update Deal Stage'), ('update_ticket_status', 'Update Ticket Status'), ('send_email_notification', 'Send Email Notification'), ('send_whatsapp', 'Send WhatsApp Message'), ('create_notification', 'Create In-App Notification'), ('create_task', 'Create Task/Activity'), ('create_ticket', 'Create Support Ticket'), ('add_tag', 'Add Tag'), ('remove_tag', 'Remove Tag'), ('update_field', 'Update Field Value'), ('add_note', 'Add Note'), ('send_email_template', 'Send Email from Template'), ('wait', 'Wait (Delay)'), ('webhook', 'Call Webhook')], max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='config',
            field=models.JSONField(default=dict, help_text='Action-specific config e.g. {user_id: 5, template_id: 3}'),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Delay before executing (0 = immediate)'),
        ),
        migrations.AlterField(
            model_name='workflowaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='field',
            field=models.CharField(help_text='e.g. lead.priority, deal.value', max_length=100),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='logic',
            field=models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=5),
        ),
        migrations.AlterField(
            model_name='workflowcondition',
            name='operator',
            field=models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Not Equals'), ('contains', 'Contains'), ('not_contains', 'Not Contains'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty'), ('in', 'In List'), ('not_in', 'Not In List')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='object_type',
            field=models.CharField(help_text='e.g. lead, deal, ticket', max_length=50),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='triggered_by',
            field=models.CharField(help_text='Event that triggered the workflow', max_length=100),
        ),
    ]
