# Generated by Django 6.0.3 on 2026-03-17 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Office 365'), ('whatsapp', 'WhatsApp Business API'), ('slack', 'Slack'), ('zapier', 'Zapier'), ('webhook', 'Generic Webhook'), ('zoho', 'Zoho CRM'), ('salesforce', 'Salesforce'), ('intercom', 'Intercom'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('twilio', 'Twilio'), ('sendgrid', 'SendGrid'), ('mailchimp', 'Mailchimp')], max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('pending', 'Pending Setup')], default='inactive', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('credentials', models.JSONField(blank=True, default=dict, help_text='Encrypted API keys / tokens')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Service-specific configuration')),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('sync_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['service'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Authentication')], max_length=20)),
                ('language', models.CharField(default='en', max_length=10)),
                ('body', models.TextField()),
                ('header', models.CharField(blank=True, max_length=200)),
                ('footer', models.CharField(blank=True, max_length=200)),
                ('variables', models.JSONField(blank=True, default=list, help_text='List of variable names used in body')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('wa_template_id', models.CharField(blank=True, help_text='Template ID from WhatsApp Business API', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wa_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WALog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_number', models.CharField(max_length=20)),
                ('body_sent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('wa_message_id', models.CharField(blank=True, max_length=200)),
                ('error', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wa_logs', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='integrations.whatsapptemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
