# Generated by Django 4.2.7 on 2026-03-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integration',
            name='extra',
            field=models.JSONField(blank=True, default=dict, help_text='phone_id, waba_id, sender_name, etc.'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='integration',
            name='service',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp Business (Meta / Gupshup)'), ('sarvam', 'Sarvam AI (Voice & Calls)'), ('gemini', 'Google Gemini AI'), ('smtp', 'Custom SMTP'), ('sendgrid', 'SendGrid'), ('razorpay', 'Razorpay Payments')], max_length=30),
        ),
        migrations.AlterField(
            model_name='whatsapplog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='variables',
            field=models.JSONField(blank=True, default=list, help_text='List of variable names in this template'),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='wa_template_id',
            field=models.CharField(blank=True, help_text='Meta-approved template name/ID', max_length=100),
        ),
    ]
