# Generated by Django 6.0.3 on 2026-03-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('indiamart', 'IndiaMART'), ('meta_leads', 'Meta Lead Ads')], max_length=30)),
                ('method', models.CharField(choices=[('pull_api', 'Pull API (Polling)'), ('push_webhook', 'Push API (Webhook)'), ('webhook', 'Webhook'), ('manual', 'Manual Sync')], max_length=20)),
                ('leads_received', models.IntegerField(default=0, help_text='Total leads received from API')),
                ('leads_created', models.IntegerField(default=0, help_text='New leads actually created')),
                ('leads_skipped', models.IntegerField(default=0, help_text='Duplicate leads skipped')),
                ('error_message', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Raw API response for debugging')),
                ('external_ids', models.JSONField(blank=True, default=list, help_text='List of external IDs processed (for dedup)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lead Import Log',
                'verbose_name_plural': 'Lead Import Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='integration',
            name='service',
            field=models.CharField(choices=[('gmail', 'Gmail'), ('outlook', 'Outlook / Office 365'), ('whatsapp', 'WhatsApp Business API'), ('gemini', 'Google Gemini AI'), ('sarvam', 'Sarvam AI'), ('indiamart', 'IndiaMART Lead Manager'), ('meta_leads', 'Meta (Facebook) Lead Ads'), ('slack', 'Slack'), ('zapier', 'Zapier'), ('webhook', 'Generic Webhook'), ('zoho', 'Zoho CRM'), ('salesforce', 'Salesforce'), ('intercom', 'Intercom'), ('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('twilio', 'Twilio'), ('sendgrid', 'SendGrid'), ('mailchimp', 'Mailchimp')], max_length=50, unique=True),
        ),
    ]
