# Generated by Django 4.2.7 on 2026-03-15 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slapolicy',
            name='escalate_after_hours',
            field=models.PositiveIntegerField(default=8, help_text='Escalate if no response after hours'),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='first_response_hours',
            field=models.PositiveIntegerField(default=4, help_text='Hours for first response'),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20),
        ),
        migrations.AlterField(
            model_name='slapolicy',
            name='resolution_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours for resolution'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('whatsapp', 'WhatsApp'), ('web', 'Web Portal'), ('chat', 'Live Chat'), ('manual', 'Manual Entry')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='csat_score',
            field=models.PositiveIntegerField(blank=True, help_text='1-5 rating', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting', 'Waiting on Customer'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned'), ('priority_changed', 'Priority Changed'), ('replied', 'Replied'), ('note_added', 'Note Added'), ('sla_breached', 'SLA Breached'), ('resolved', 'Resolved'), ('reopened', 'Reopened'), ('csat_received', 'CSAT Received')], max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketcategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Visible to contact if False = internal note'),
        ),
        migrations.AlterField(
            model_name='ticketreply',
            name='reply_type',
            field=models.CharField(choices=[('reply', 'Reply'), ('note', 'Internal Note'), ('system', 'System Event')], default='reply', max_length=10),
        ),
    ]
